export const START_GAME_REQUEST = 'app/Board/START_GAME_REQUEST';
export const START_GAME_RESPONSE = 'app/Board/START_GAME_RESPONSE';

export const START_GAME_CPU_VS_CPU_REQUEST =
  'app/Board/START_GAME_CPU_VS_CPU_REQUEST';
export const START_GAME_CPU_VS_CPU_RESPONSE =
  'app/Board/START_GAME_CPU_VS_CPU_RESPONSE';
